// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

int2 cpos;

int2 dime;
int numStates;
RWStructuredBuffer<uint> popcount;
StructuredBuffer<float> popBuffer;

[numthreads(32,32,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    int index = (cpos.x + id.x - 16) + dime.x * (cpos.y + id.y - 16);
    InterlockedAdd(popcount[0], popBuffer[index]);
}




