// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

int2 dime;

int numStates;
RWStructuredBuffer<uint> popcount;
StructuredBuffer<int> teamOf;
StructuredBuffer<float> popBuffer;

[numthreads(32,32,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    int index = (id.y * dime.x) + id.x;
    InterlockedAdd(popcount[teamOf[index]], popBuffer[index]);
}
