// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> BLayer;
RWTexture2D<float4> CamIn;

[numthreads(32,32,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    float4 input = CamIn[id.xy].rgba;
    float inputWeight = 0.8;
    CamIn[id.xy] = 1 * (1 - inputWeight) * BLayer[id.xy] + CamIn[id.xy] * inputWeight;
}
